# docker-compose.yml
version: '3.7'
services:
  jenkins:
    build: .
    privileged: true
    ports:
      - 8080:8080
    container_name: my-jenkins-3
    environment:
      JAVA_OPTS: -Djenkins.install.runSetupWizard=false
      JENKINS_OPTS: --argumentsRealm.roles.user=admin --argumentsRealm.passwd.admin=admin --argumentsRealm.roles.admin=admin
    volumes:
      - ~/jenkins_data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock